<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Serilog" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Order.Processing.Domain\Order.Processing.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Features\Orders\CreateOrder\" />
    <Folder Include="Features\Orders\GetOrder\" />
    <Folder Include="Features\Orders\GetAllOrders\" />
    <Folder Include="Features\Orders\UpdateOrder\" />
    <Folder Include="Features\Payments\GetPaymentStatus\" />
    <Folder Include="Features\Payments\ProcessPayment\" />
  </ItemGroup>
</Project>
