<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Order.Processing.Application\Order.Processing.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Order.Processing.Api.Tests" />
  </ItemGroup>

</Project>
